title: Legera
author: Legera
description: > 
  Legera's website

minima:
  skin: dark

theme: minima

header_pages:
  - portfolio.md
  - vortex.md

plugins:
  - jekyll-titles-from-headings
  
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
